import './globals.css'
import { Montserrat } from 'next/font/google'
import Header from '@/components/Header/Header';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const layoutStyles = {
  fontFamily: 'var(--font-montserrat)',
};

export const metadata = {
  title: "Videojuegos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.variable} style={layoutStyles}>
        <Header />
        {children}
      </body>
    </html>
  );
}
